don't lazy-load templates into the pyfakefs
lazy-loading the templates into the pyfakefs seems to cause some
manifest tests to become unreliable, with an error:

  OSError: [Errno 9] Bad file descriptor in the fake filesystem

Eager-loading the templates appears to resolve these flaky tests.